version: '3.3'
services:
  home-users-api:
    build: .
    ports:
      - '0.0.0.0:8080:8080'
    depends_on:
      - users_db
    env_file: .env
    volumes:
      - .:/go/src/github.com/Pawelek242/home_users-api

  users_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    # TODO: Doesnt work :-/
    # volumes:
    #   - /generated/mysql:/var/lib/mysql
